services:
  - type: web
    name: fastapi-file-processor
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn n8n_api_withhistorical:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: "10000"
